# Generated by Django 5.1.7 on 2025-03-22 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("year", models.IntegerField(default=2018)),
                ("file", models.FileField(upload_to="posts/media/uploads")),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="posts", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.department",
                    ),
                ),
                (
                    "supervisors",
                    models.ManyToManyField(
                        related_name="supers", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
