# Generated by Django 5.1.7 on 2025-03-22 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Lecturer", "Lecturer"),
                            ("Assistant Professor", "Assistant Professor"),
                            ("Associate Professor", "Associate Professor"),
                            ("Professor", "Professor"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "dept",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Computer Science and Engineering",
                                "Computer Science and Engineering",
                            ),
                            (
                                "Electrical and Electronic Engineering",
                                "Electrical and Electronic Engineering",
                            ),
                            (
                                "Information and Communication Engineering",
                                "Information and Communication Engineering",
                            ),
                            ("Civil Engineering", "Civil Engineering"),
                            ("Mechanical Engineering", "Mechanical Engineering"),
                            ("Business Administration", "Business Administration"),
                        ],
                        default=None,
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, default=None, max_length=11, null=True
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(default=None, upload_to="accounts/media/images/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
