# Generated by Django 4.2.13 on 2024-07-31 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('assistant professor', 'Assistant Professor'), ('associate professor', 'Associate Professor'), ('professor', 'Professor')], max_length=100)),
                ('dept', models.CharField(blank=True, choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electrical and Electronic Engineering', 'Electrical and Electronic Engineering'), ('Information and Communication Engineering', 'Information and Communication Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Business Administration', 'Business Administration')], default=None, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_profile/media/images/')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
